# Khepera III Robot
robot:
  max_transl_vel: 0.3148 # m/s forward speed
  max_ang_vel: 2.2763 # rad/s turn rate
  bottom_plate: [[-0.024, 0.064],
                 [0.033, 0.064],
                 [0.057, 0.043],
                 [0.074, 0.010],
                 [0.074, -0.010],
                 [0.057, -0.043],
                 [0.033, -0.064],
                 [-0.025, -0.064],
                 [-0.042, -0.043],
                 [-0.048, -0.010],
                 [-0.048, 0.010],
                 [-0.042, 0.043]]
  sensor:
    min_range: 0.02
    min_read_value: 18
    max_range: 0.2
    max_read_value: 3960
    poses: [[-0.038, 0.048, 128],
            [0.019, 0.064, 75],
            [0.050, 0.050, 42],
            [0.070, 0.017, 13],
            [0.070, -0.017, -13],
            [0.050, -0.050, -42],
            [0.019, -0.064, -75],
            [-0.038, -0.048, -128],
            [-0.048, 0.000, 180]]
  wheel:
    radius: 0.021
    base_length: 0.0885
    ticks_per_rev: 2765
    max_speed: 15.0  # in rad/s

slam:
  robot_state_size: 3
  landmark_state_size: 2
  distance_threshold: 0.3
